apiVersion: v1
kind: Pod
metadata:
  name: prom-exporter-benchmarking-ms
spec:
  volumes:
    - name: result-storage
      persistentVolumeClaim:
        claimName: result-storage-claim
  containers:
    - name: prom-exporter-benchmarking-ms
      image: xwoodpecker/prom-exporter-benchmarking-ms
      envFrom:
        - configMapRef:
            name: general-config
        - secretRef:
            name: general-secrets
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "1000m"
      volumeMounts:
        - mountPath: "/out"
          name: result-storage
  restartPolicy: Never