{
 "title": "First Dashboard for Aggregator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Microservice Metriken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Microservice Activity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "microservice_activity", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Running Pods by Deployment",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"torvalds\", deployment=~\".*-deployment\" }",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "RabbitMq Statistics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "Queues" },
    { "expr": "rabbitmq_consumers", "legendFormat": "Consumers" },
    { "expr": "rabbitmq_connections", "legendFormat": "Connections" }
   ]
  },
  { "title": "Sensor Metriken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Saarland Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-avg\"}",
     "legendFormat": "Durchschnitt"
    },
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-max\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-min\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  { "title": "Placeholder", "type": "timeseries", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 } },
  {
   "title": "Saarland Taupunkt Durchschnitt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-saarland-avg\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  { "title": "Placeholder", "type": "timeseries", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 } },
  {
   "title": "Saarland Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-avg\"}",
     "legendFormat": "Durchschnitt"
    },
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-max\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-min\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  { "title": "Placeholder", "type": "timeseries", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 } },
  {
   "title": "Saarbrücken Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor1\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Moscow Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor2\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Saarbrücken Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-1\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Moscow Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-2\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Saarbrücken Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor1\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Moscow Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor2\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Antarctica Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor3\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Rome Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor4\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Antarctica Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-3\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Rome Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-4\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Antarctica Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor3\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Rome Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor4\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "New York City Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor5\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Tokyo Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/temperature/sensor6\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "New York City Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-5\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Tokyo Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-6\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "New York City Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor5\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Tokyo Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensorname=\"data/aggregator/humidity/sensor6\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{datatype=\"temperature\"}) without (instance, pod)",
     "legendFormat": "{{sensorname}}"
    }
   ]
  },
  {
   "title": "Wo Nass?",
   "type": "stat",
   "gridPos": { "h": 37, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_measurement{datatype=\"water\"}",
     "legendFormat": "{{sensorname}}"
    }
   ]
  },
  {
   "title": "Taupunkte",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{datatype=\"dewpoint\"}) without (instance, pod)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeiten",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{datatype=\"humidity\"}) without (instance, pod)",
     "legendFormat": "{{sensorname}}"
    }
   ]
  }
 ]
}