{
 "title": "First Dashboard for Aggregator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Microservice Metriken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Microservice Activity",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "microservice_activity", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Running Pods by Deployment",
   "type": "stat",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"torvalds\", deployment=~\".*-deployment\" }",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "type": "timeseries", "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Number of recent errors",
   "type": "stat",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(logback_events_total{level=\"error\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(jvm_buffer_memory_used_bytes)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Server Request Count",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod)(http_server_requests_seconds_count)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "RabbitMQ Metriken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queues", "legendFormat": "Queues" },
    { "expr": "rabbitmq_connections", "legendFormat": "Connections" },
    { "expr": "rabbitmq_channels", "legendFormat": "Channels" },
    { "expr": "rabbitmq_consumers", "legendFormat": "Consumers" },
    {
     "expr": "sum(rabbitmq_channels) - sum(rabbitmq_channel_consumers)",
     "legendFormat": "Publishers"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)",
     "legendFormat": "Ready Messages"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacked)",
     "legendFormat": "Unacknowledged Messages"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]))"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[60s])) +\nsum(rate(rabbitmq_channel_messages_delivered_total[60s])) +\nsum(rate(rabbitmq_channel_messages_delivered_ack_total[60s])) +\nsum(rate(rabbitmq_channel_get_total[60s])) +\nsum(rate(rabbitmq_channel_get_ack_total[60s]))"
    }
   ]
  },
  { "title": "Sensor Metriken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Saarland Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-avg\"}",
     "legendFormat": "Durchschnitt"
    },
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-max\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "group_measurement{datatype=\"temperature\", combinator=\"double-min\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{datatype=\"temperature\"}) without (instance, pod)",
     "legendFormat": "{{location_name}}"
    }
   ]
  },
  {
   "title": "Saarland Taupunkt Durchschnitt",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-saarland-avg\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Taupunkte",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{datatype=\"dewpoint\"}) without (instance, pod)",
     "legendFormat": "{{location_name}}"
    }
   ]
  },
  {
   "title": "Saarland Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-avg\"}",
     "legendFormat": "Durchschnitt"
    },
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-max\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "group_measurement{datatype=\"humidity\", combinator=\"double-min\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeiten",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{datatype=\"humidity\"}) without (instance, pod)",
     "legendFormat": "{{location_name}}"
    }
   ]
  },
  {
   "title": "Wie oft regnet es im Saarland?",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group_measurement{datatype=\"water-sum\", combinator=\"true-count\"}",
     "legendFormat": "Anzahl Kreisstädte mit Regen"
    }
   ]
  },
  {
   "title": "Wo regnet es?",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_measurement{datatype=\"water\"}",
     "legendFormat": "{{location_name}}"
    }
   ]
  },
  {
   "title": "Saarbrücken Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor1\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Moscow Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor2\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Saarbrücken Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-1\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Moscow Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-2\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Saarbrücken Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor1\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Moscow Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor2\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Antarctica Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor3\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Rome Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor4\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Antarctica Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-3\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Rome Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-4\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Antarctica Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor3\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Rome Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor4\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "New York City Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor5\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "Tokyo Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/temperature/sensor6\"}) without (instance, pod)",
     "legendFormat": "Temperatur"
    }
   ]
  },
  {
   "title": "New York City Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-5\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "Tokyo Taupunkt",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(group_measurement{group=\"dewpoint-group-6\"}) without (instance, pod)",
     "legendFormat": "Taupunkt"
    }
   ]
  },
  {
   "title": "New York City Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor5\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  },
  {
   "title": "Tokyo Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "sum(sensor_measurement{sensor_name=\"data/aggregator/humidity/sensor6\"}) without (instance, pod)",
     "legendFormat": "Luftfeuchtigkeit"
    }
   ]
  }
 ]
}