apiVersion: v1
kind: ConfigMap
metadata:
  name: general-config
data:
  #BROKER
  BROKER_HOST: "10.100.227.136"
  BROKER_PORT_MQTT: "8883"
  BROKER_PORT_AMQP: "5671"
  #BROKER_MANAGEMENT_PORT: "15672"
  CA_FILE: "MIIDRTCCAi2gAwIBAgIJAP/I/6ertm4DMA0GCSqGSIb3DQEBCwUAMDExIDAeBgNVBAMMF1RMU0dlblNlbGZTaWduZWR0Um9vdENBMQ0wCwYDVQQHDAQkJCQkMB4XDTIxMDMwOTA3MDA0MloXDTMxMDMwNzA3MDA0MlowMTEgMB4GA1UEAwwXVExTR2VuU2VsZlNpZ25lZHRSb290Q0ExDTALBgNVBAcMBCQkJCQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCgWpBbxeMdsELnXCdpibIBxzivEpTsnbIQs5E815S8fXrOTntw2xOGrd0QuASwWVzDszc4q/OZv8b1k6A37PAL7NUDGJH5tBYIHV4W9EZdsh2PnG7K9fZ06/ivL/r+eZwwGguO8FZiyoqej8xnrMZR5bCd7x8kzfbGiZF6f2T728NFPixh7VBKfvzAaKtXdSudCjaAkWU0W7nL55OXDh+34v65DaS9oHRzmKvhZcV50lvAuvxS6SbGXNrSUc3yp0RwY4diwPYCu3OPoE/q51oLdhdbfF4x5nysM5ZEyy1nrY3JsRGfwO4odywPbqYTHJOL42pjBXtkTWXJIMhHMV4rAgMBAAGjYDBeMAsGA1UdDwQEAwIBBjAdBgNVHQ4EFgQU8lbr5MLijZfebTS5oe3o3PjoHFQwHwYDVR0jBBgwFoAU8lbr5MLijZfebTS5oe3o3PjoHFQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEADlv3hkQjOnm5OYJRtomip2ZIA7htZqMDu6AcImfFRcERDikPCvTx/MIQ4uJHee4T6RimtVaa3gXg9EnAgZSIT5k58Gm0NC9G/gjbrXgWZPgm5hDDsM5JPxaMoHUCcVWABs57EHyF2xMsa7RkgAdHB2w81WZuJvrscJ7we/emuhz1B+151bNEKu5eWB0migfkxIAmDf/XJlzoSFnoNIx6ZRhtIyhqi10Vhs5zq4pxYKvZaIinpxoqm0nt9H6f2sXcF12Cgfx50Pt5iwX6PROA4NKMPC5iQCGwE6bFbmkwxXfYucSsNvzUXTdyElBwn2MY9L7yQtz+68dnE4uEVhPmAQ=="
  CLIENT_CERT_FILE: "MIIDRzCCAi+gAwIBAgIBAjANBgkqhkiG9w0BAQsFADAxMSAwHgYDVQQDDBdUTFNHZW5TZWxmU2lnbmVkdFJvb3RDQTENMAsGA1UEBwwEJCQkJDAeFw0yMTAzMDkwNzAwNDJaFw0zMTAzMDcwNzAwNDJaMC4xGzAZBgNVBAMMEmRzbC1jbHVzdGVyLW1hc3RlcjEPMA0GA1UECgwGY2xpZW50MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuCgAZRZbzie6aihpzqOmh2hyv/Xk0VWLBN7LfjyDB8RqzgerCrwWn6DX31pvFosF7AStLpyPNwYTWVg5mHWRVOEeD0euQ+QsSERBqItCT4P03Q6FfLqkgZyPxJ56DhwKtON19hzhFM/Te/PtAKMeekqLj5coi+Yiv4CHJmrl6iTkLxy5BT+6LPCY+Xz4b6FgfjMFURT9+gbedSjBRByGVyu8AvEzuvm1KoOkZKZUsM6EI8N3gleYsh5nvHPj5ZmiszKticcOIyJ8AoYCADUlmVMQC5J0lFWveEJ53k0/VdBsCC/CuLL4N2LH1ZZ5ZRWMnZsfIYW4sf2ZpBlTW37/uwIDAQABo20wazAJBgNVHRMEAjAAMAsGA1UdDwQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDAjA8BgNVHREENTAzghJkc2wtY2x1c3Rlci1tYXN0ZXKCEmRzbC1jbHVzdGVyLW1hc3RlcoIJbG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4IBAQBceAi2/kQVWIVL5E58bbLHrysXpIIdNZIACz5AwI7mefWR0ALqzfaHgcin0li3ZRpp9+vjsyc60tQvCqMSIb4KcxNBAoxVqn3UmLQk3IgC2Vtoe9Drsn9llBw3smoeAeHLxEdj1WaVU9fPzNi4Xi0SSgoC9BEyym01FbuqZDE2Iuekw3sbjGrwNVYX0FoEhBRyQhJqnh2E97OPv2wGKtiSg5wkNOwNZA3UicfHaiBf9idXxH8Yold80wAl2NnpZ7Kce1s7hFu8CArwbfTGsYjWFvAtzy4GtqBx/ZfQSLeJR1iUyF9SjVjMlQ+gb2xmC4kf7KaN3YWlMHvR1CTu26hV"
  CLIENT_KEY_FILE: "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4KABlFlvOJ7pqKGnOo6aHaHK/9eTRVYsE3st+PIMHxGrOB6sKvBafoNffWm8WiwXsBK0unI83BhNZWDmYdZFU4R4PR65D5CxIREGoi0JPg/TdDoV8uqSBnI/EnnoOHAq043X2HOEUz9N78+0Aox56SouPlyiL5iK/gIcmauXqJOQvHLkFP7os8Jj5fPhvoWB+MwVRFP36Bt51KMFEHIZXK7wC8TO6+bUqg6RkplSwzoQjw3eCV5iyHme8c+PlmaKzMq2Jxw4jInwChgIANSWZUxALknSUVa94QnneTT9V0GwIL8K4svg3YsfVlnllFYydmx8hhbix/ZmkGVNbfv+7AgMBAAECggEAWpn7j8BPTH7JPP9DBxIGlSnzArREbiUK70t5jFLTGFgvP8wP/4kIDGMCsfV5H/sn37VxSrRl1WlczaEVPQfih4L12ginGOnCS4+hSf2xkxNVvggt7m6ZDtdq+A4L+LMdJV+fIoWUyztwTdR1btHR5dKVFQEGRsXjpJnkZCdFlErafmuYS3fjDqMH/EN1tDJmEy30GHH9lEAKkBKk/sJrS1Nyd522dzYXcWl9QAzBQP831Ale3WDkOXNRYFde6K2FJfiSG9bLjNeiObAj7fbFs5ewmP/KgEbsWfzSrenC/dXQK8WP7yNAm2c043oZGtge0o1vDG2HJlm4+mBLpfMBQQKBgQDaAsj8JKAXi9MlkW1s+j5nDYDN/1Z7WGmXtxOsc5oqI6FiaceZA55EQ969XBxONcyDAmbtEIG13/ZvStuPf40JsqA5piUHUGVqPxXHdAqrZw9Cx7tuAo0Dk59Z/S8wfh+1KGi1qgUMvz9lxFlWrYW2SjoqKldN82UdUl7daL6dmwKBgQDYPwAmnCp9GB1byJSI/fTrgF5xKjQpIgzSoZ3p57SsdTpJoYugmaRzCmm/E5NH1Y5ziBNuyONtJtg9xqWuqi8zRlk07pcpe59j5avoFbtO5fH9U5bYU/xanXLKTKIo2zF4+LXZFh4N6BLdvR4iZmBmbRHRKqBEjjRClLaoTMhYYQKBgGzeDS3UwFlhysws5j8QbA8cMCEujCpGSVyo4NsyU18Nse6qMjFYHDWsytM25y+rL/iQP4PMxWlkcPS8pg3vvSeFmvuO21jerfYzkJWsfhOAAJ/xi8hw36hUlLPkeic2JHFbv4ZQY/ssmeUg+xgMyQPx5z/dKwHTNMBCvPrF7sJXAoGAQ7KtdGjtcE4tWr+XqK+Ajn2Yk2r3+2yagRJxonmUeW0Vu1lkofmXnyBCbLxPHmz/9LFEDCm98Tz485YN5nmG31GFuel7z1PRWW/ceoLbKd8Y/ArALadVWHT0K9sD5TCB83JBU931uLrPtTVwiqpsQYSh0E6879lpCPMPn+6xxeECgYAITqA9Xzxgj2bNnUAcqfT0FSGLPNyh0zF9Q9nKFk3tKyJUDniB70n4LSx9+EApFQvHO6OFKmdxn36rtlrCnXE/Gj3yyW8NwxhLCHb09GVtMLlZ6xcXTYue90GWGDbvEh3+Ftv7Q38euDg9zc3ES+Jg6VaBVFKnnLycQQbNQQn2Gw=="
  #MINIO
  MINIO_ENDPOINT: "http://my-minio:9000"
  #MEMCACHED
  MEMCACHED_HOST: "my-memcached"
  MEMCACHED_PORT: "11211"
  #MYSQL
  spring.datasource.url: "jdbc:mysql://my-mysql:3306/test"
  #TEMPERATURE MS
  TEMPERATURE_QUEUE: temperature
  TEMPERATURE_TOPICS: data/aggregator/temperature/#
  TEMPERATURE_BUCKET: aggregator
  TEMPERATURE_SENSOR_TYPE: temperature
  #HUMIDITY MS
  HUMIDITY_QUEUE: humidity
  HUMIDITY_TOPICS: data/aggregator/humidity/#
  HUMIDITY_BUCKET: aggregator
  HUMIDITY_SENSOR_TYPE: humidity
  EXPORT_HUMIDITY_DATA_AS_METRIC: "true"
  #TEMPERATURE AGGREGATOR
  TEMPERATURE_AGGREGATOR_MICROSERVICE_QUEUE: temperature-group
  TEMPERATURE_AGGREGATOR_MICROSERVICE_BUCKET: aggregator
  TEMPERATURE_AGGREGATOR_MICROSERVICE_GROUP_TYPE_NAME: temperature-group
  TEMPERATURE_DATA_TYPE_NAME: temperature
  EXPORT_TEMPERATURE_DATA_AS_METRIC: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: general-secrets
type: Opaque
stringData:
  #BROKER
  BROKER_USERNAME: user
  BROKER_PASSWORD: DgBe3RZVvZ
  #MINIO
  MINIO_ACCESSKEY: KIcwliRROr
  MINIO_SECRETKEY: YMsH1r8mhk9as68H7Ie9PCxGTsjNMveMqBJibSr4
  #MYSQL
  spring.datasource.username: root
  spring.datasource.password: QmnfjkLnKo

