apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-monitor
  labels:
    release: my-prom
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
    - port: http

