apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: airquality-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airquality-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: microservice_activity
        target:
          type: AverageValue
          averageValue: 75