FROM openjdk:14-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Xms512M", "-Xmx1024M", "-jar", "/app.jar", "de.htw.saar.smartcity.aggregator.exporter.benchmarking.ExporterMicroserviceBenchmark"]