apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-service-monitor
  labels:
    release: my-prom
spec:
  selector:
    matchLabels:
      app: rabbitmq
  endpoints:
    - port: prometheus