apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: water-service-monitor
  labels:
    release: my-prom
spec:
  selector:
    matchLabels:
      app: water-ms
  endpoints:
    - port: http