apiVersion: v1
kind: Pod
metadata:
  name: benchmarking-ms
spec:
  containers:
    - name: benchmarking-ms
      image: xwoodpecker/benchmarking-ms
      envFrom:
        - configMapRef:
            name: general-config
        - secretRef:
            name: general-secrets