apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: result-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: result-storage-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/out"