apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: humidity-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: humidity-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        metric:
          name: rabbitmq_queue_messages
          selector: {matchLabels: {queue: "humidity"}}
        describedObject:
          apiVersion: "/v1"
          kind: Service
          name: rabbitmq-service
        target:
          type: Value
          value: 20