apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: humidity-service-monitor
  labels:
    release: my-prom
spec:
  selector:
    matchLabels:
      app: humidity-ms
  endpoints:
    - port: http

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: humidity-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: humidity-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: microservice_activity
        target:
          type: AverageValue
          averageValue: 75