apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: temperature-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temperature-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: messages
        target:
          type: AverageValue
          averageValue: 1
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60