apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: temperature-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: temperature-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        metric:
          name: rabbitmq_queue_messages_ready
          selector: {matchLabels: {queue: "temperature"}}
        describedObject:
          apiVersion: "/v1"
          kind: Service
          name: rabbitmq-service
        target:
          type: Value
          value: 20
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120