apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-historic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-historic-ms
  template:
    metadata:
      labels:
        app: my-historic-ms
    spec:
      containers:
        - name: my-historic-ms
          image: user/my-historic-ms
          envFrom:
            - configMapRef:
                name: general-config
            - secretRef:
                name: general-secrets


